apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestreamrecorderbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestreamrecorderbackend
  template:
    metadata:
      labels:
        app: livestreamrecorderbackend
    spec:
      containers:
        - name: livestreamrecorderbackend
          image: ghcr.io/recorder-moe/livestreamrecorderbackend
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 300Mi
            requests:
              memory: 100Mi
          env:
            - name: CORS_SUPPORT_CREDENTIALS
              value: "true"
            - name: FUNCTIONS_WORKER_RUNTIME
              value: "dotnet"
            - name: CORS_ALLOWED_ORIGINS
              value: "https://recorder.moe"
            - name: FrontEndUri
              value: "https://recorder.moe"
            - name: AzureWebJobsStorage
              value: "BLOB_CONNECTIONSTRING"
            - name: Seq_ServerUrl
              value: "https://seq.recorder.moe"
            - name: Seq_ApiKey
              value: "YOUR_API_KEY"
            - name: ConnectionStrings_Private
              value: "DB_CONNECTIONSTRINGS_PRIVATE"
            - name: ConnectionStrings_Public
              value: "DB_CONNECTIONSTRINGS_PUBLIC"
            - name: Blob_ConnectionString
              value: "BLOB_CONNECTIONSTRING"
            - name: Blob_ContainerName
              value: "BLOB_CONTAINERNAME_PRIVATE"
            - name: Blob_ContainerNamePublic
              value: "BLOB_CONTAINERNAME_PUBLIC"
            - name: Registration_allowed
              value: "true"
            - name: GITHUB_PROVIDER_AUTHENTICATION_ID
              value: "GITHUB_CLIENTID"
            - name: GITHUB_PROVIDER_AUTHENTICATION_SECRET
              value: "GITHUB_SECRET"