apiVersion: v1
kind: ConfigMap
metadata:
  name: livestreamrecorder-config
data:
  config.jsonc: |-
    {
      // Google Analytics, keep empty to disable
      // G-XXXXXXXXXX
      "GA_TRACKING_ID": "G-XXXXXXXXXX",

      // Azure Blob storage endpoint
      // https://myaccount.blob.core.windows.net/mycontainer
      // This one is for videos. (private access)
      "blobstorage": "BLOB_CONTAINERNAME_PRIVATE",
      // This one is for images. (public access)
      "blobstorage_public": "BLOB_CONTAINERNAME_PUBLIC",

      // Azure COSMOS DB
      // https://myaccount.documents.azure.com:443/
      "endpoint": "DB_CONNECTIONSTRINGS_PUBLIC_ENDPOINT",
      // Read-only Key!!!
      "key": "DB_CONNECTIONSTRINGS_PUBLIC",

      // OAuth2
      "clientId_google": "GOOGLE_CLIENTID",
      "clientId_github": "GITHUB_CLIENTID",
      "clientId_microsoft": "MICROSOFT_CLIENTID",
      "clientId_discord": "DISCORD_CLIENTID",

      // Azure Function API endpoint (LivestreamRecorderBackend)
      "apiUrl": "",

      // Admin email, displayed in the FAQ page
      "adminEmail": "ADMIN_EMAIL"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestreamrecorderfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestreamrecorderfrontend
  template:
    metadata:
      labels:
        app: livestreamrecorderfrontend
    spec:
      containers:
        - name: livestreamrecorderfrontend
          image: ghcr.io/recorder-moe/livestreamrecorderfrontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 300Mi
            requests:
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.jsonc
              subPath: config.jsonc
      volumes:
        - name: config-volume
          configMap:
            name: livestreamrecorder-config