# host is your host name without https://
# When using docker desktop kubernetes install ingress-nginx controller and use 'kubernetes.docker.internal' as host
# https://kubernetes.github.io/ingress-nginx/deploy/#docker-desktop
host: kubernetes.docker.internal

settings:
  # gATrackingID is Google Analytics tracking id
  # Input empty string to disable
  gATrackingID: G-XXXXXXXXXX
  # adminEmail will display on the page
  adminEmail: your@email.com
  # registrationAllowed setting determines whether users are allowed to register.
  # If set to false, only the first registered user will be allowed and will become an admin.
  registrationAllowed: "true"

azureBlob:
  storageAccountName: myrecorder
  storageAccountKey: YOUR_KEY
  # public is the public access blob container for images.
  public:
    endpoint: https://myaccount.blob.core.windows.net/mypubliccontainer
    containerName: mypubliccontainer
  # private is the private access blob container for videos.
  private:
    endpoint: https://myaccount.blob.core.windows.net/myprivatecontainer
    containerName: myprivatecontainer
  # retentionDays is the number of days to keep the video files.
  retentionDays: 4

azureCosmosDB:
  # public is the database for Videos, Channels data.
  public:
    endpoint: https://myaccount.documents.azure.com:443/
    readonlyKey: DB_PUBLIC_READONLY_KEY
    readWriteKey: DB_PUBLIC_READWRITE_KEY
  # private is the database for User data.
  private:
    endpoint: https://myprivateaccount.documents.azure.com:443/
    readWriteKey: DB_PRIVATE_READWRITE_KEY

# oAuth2 is the configuration for OAuth 2.0 login.
# !Notice that you MUST setup at least one provider since this system is only using OAuth 2.0 for authentication.
oAuth2:
  # Input empty string to disabled
  google:
    clientID: GOOGLE_CLIENTID
  gitHub:
    clientID: GITHUB_CLIENTID
    clientSecret: GITHUB_SECRET
  microsoft:
    clientID: MICROSOFT_CLIENTID
  discord:
    clientID: DISCORD_CLIENTID

seq:
  serverUrl: https://12.34.56.78
  apiKey: YOUR_API_KEY

twitch:
  enabled: false
  clientID: TWITCH_CLIENTID
  clientSecret: TWITCH_SECRET

discord:
  enabled: false
  webhook: ""
  webhookWarning: ""
  webhookAdmin: ""
  mention:
    channel: "<@&1088065141721022535>"
    deleted: "<@&1088065179855618108>"
    admin: "<@&1068992903797542934>"
  emotes:
    recordermoe: "<:logo:1087793006922436748>"
    youtube: "<:youtube:1087785692605722767>"
    twitch: "<:twitch:1087786596138491934>"
    twitcasting: "<:twitcasting:1087785961963929742>"
    fc2: "<:fc2:1113124319346823240>"

heartbeat:
  enabled: false
  endpoint: ""

kubernetes:
  clusterDomain: recorder.moe.local

  # ingressClassName is for frontend and backend ingress settings.
  # When using Traefik set this to "" (empty string).
  # When using docker desktop kubernetes install ingress-nginx controller and set this to "nginx".
  ingressClassName: nginx

  frontend:
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 300Mi
      requests:
        memory: 100Mi
  backend:
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 300Mi
      requests:
        memory: 100Mi
  service:
    # service replicas is limited to 1
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        memory: 500Mi

    # pvcName is the name for PersistentVolumeClaim for service.
    # !Only used when nfs.enable is false.
    # Please create this PVC in the same namespace manually.
    pvcName: shared-volume-pvc

  nfs:
    enable: true

    # customPVC is the name for PersistentVolumeClaim used as an underlay for NFS.
    # !Please create the PVC in 'kube-system' namespace manually. (With storage about 10Gi)
    # Keep this empty to use any other solutions below.
    customPVC: ""

    # bindHostDirectory bind the host directory into nfs-server for share.
    # This is not recommended and can't used with customPVC.
    # !Note that this is not working with Docker Desktop with Windows.
    # Issue: https://github.com/sjiveson/nfs-server-alpine/issues/43
    bindHostDirectory: false
    hostPath: /recordermoe-nfs

    # If none of the above is set, emptyDir will be used.
