# Your host name without https://
# When using docker desktop kubernetes, install ingress-nginx controller and use 'kubernetes.docker.internal' as host
# https://kubernetes.github.io/ingress-nginx/deploy/#docker-desktop
host: kubernetes.docker.internal

settings:
  # Google Analytics, input empty string to disable
  gATrackingID: G-XXXXXXXXXX
  # This will display on the page
  adminEmail: your@email.com
  # You can only register one account if this is "false"
  registrationAllowed: "true"

azureBlob:
  connectionString: DefaultEndpointsProtocol=https;AccountName=myrecorder;AccountKey=YOUR_KEY;EndpointSuffix=core.windows.net
  public:
    # This is a public access blob container for images.
    endpoint: https://myaccount.blob.core.windows.net/mypubliccontainer
    containerName: mypubliccontainer
  private:
    # This is a private access blob container for videos.
    endpoint: https://myaccount.blob.core.windows.net/myprivatecontainer
    containerName: myprivatecontainer

azureCosmosDB:
  # This is the database for Videos, Channels data.
  public:
    endpoint: https://myaccount.documents.azure.com:443/
    readonlyKey: DB_PUBLIC_READONLY_KEY
    readWriteKey: DB_PUBLIC_READWRITE_KEY
  # This is the database for User data.
  private:
    endpoint: https://myprivateaccount.documents.azure.com:443/
    readWriteKey: DB_PRIVATE_READWRITE_KEY

oAuth2:
  # Input empty string to disabled
  google:
    clientID: GOOGLE_CLIENTID
  gitHub:
    clientID: GITHUB_CLIENTID
    clientSecret: GITHUB_SECRET
  microsoft:
    clientID: MICROSOFT_CLIENTID
  discord:
    clientID: GOOGLE_CLIENTID

seq:
  serverUrl: https://12.34.56.78
  apiKey: YOUR_API_KEY

kubernetes:
  clusterDomain: recorder.moe.local
  frontend:
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 300Mi
      requests:
        memory: 100Mi
  backend:
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 300Mi
      requests:
        memory: 100Mi
