apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recorder.fullname" . }}-config
  labels:
  {{- include "recorder.labels" . | nindent 4 }}
data:
  config.jsonc: |-
    {
      "GA_TRACKING_ID": "{{ .Values.settings.gATrackingID }}",
      "blobstorage": "{{ .Values.azureBlob.private.endpoint }}",
      "blobstorage_public": "{{ .Values.azureBlob.public.endpoint }}",
      "endpoint": "{{ .Values.azureCosmosDB.public.endpoint }}",
      "key": "{{ .Values.azureCosmosDB.public.readonlyKey }}",
      "clientId_google": "{{ .Values.oAuth2.google.clientID }}",
      "clientId_github": "{{ .Values.oAuth2.gitHub.clientID }}",
      "clientId_microsoft": "{{ .Values.oAuth2.microsoft.clientID }}",
      "clientId_discord": "{{ .Values.oAuth2.discord.clientID }}",
      "apiUrl": "https://{{ .Values.host }}",
      "adminEmail": "{{ .Values.settings.adminEmail }}"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recorder.fullname" . }}-frontend
  labels:
  {{- include "recorder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubernetes.frontend.replicas }}
  selector:
    matchLabels:
      app: recorderfrontend
    {{- include "recorder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: recorderfrontend
      {{- include "recorder.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetes.clusterDomain }}
        image: ghcr.io/recorder-moe/livestreamrecorderfrontend:latest
        name: recorderfrontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {{- toYaml .Values.kubernetes.frontend.resources | nindent
          10 }}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/config.jsonc
          name: config-volume
          subPath: config.jsonc
      volumes:
      - configMap:
          name: {{ include "recorder.fullname" . }}-config
        name: config-volume