apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "recorder.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "recorder.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "recorder.fullname" . }}-backend-service'
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "recorder.fullname" . }}-frontend-service'
            port:
              number: 80
        path: /
        pathType: Prefix